name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/github_actions_key
          chmod 600 ~/.ssh/github_actions_key
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/github_actions_key
          ssh -i ~/.ssh/github_actions_key -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "echo 'SSH connection test successful'"

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/github_actions_key -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_PATH }}
            
            # Install Node.js 18 if not available
            if ! command -v node &> /dev/null || [[ "$(node --version | cut -d'v' -f2 | cut -d'.' -f1)" -lt 18 ]]; then
              echo "Installing Node.js 18..."
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            
            # Verify Node.js version
            echo "Node.js version: $(node --version)"
            echo "npm version: $(npm --version)"
            
            # Configure Git SSH
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/github_actions_key 2>/dev/null || echo "No SSH key found in ~/.ssh/github_actions_key"
            
            # Clean install
            rm -rf node_modules package-lock.json
            git pull origin main
            npm install
            npm run build
            pm2 restart ecosystem.config.js
          EOF
